### ISSUE TITLE
Powershell not going through because of Errno 2 No such file or directory

### ISSUE THREAD

**Issue by cbnsti** [JannikBirn/palworld-host-save-fix#26]
I try to run the powershell line but no matter what I do I keep getting the same error, even though I have Palworld-save-tools and fix-host-save.py

C:\Users\hunte\AppData\Local\Microsoft\WindowsApps\python.exe: can't open file 'C:\\Users\\hunte\\fix-host-save.py': [Errno 2] No such file or directory

Need HELP Please

**Comment by JannikBirn** [comment]
Are you sure that the path is correct? The repository/directory is named with "-" but the file got "_" in the name.

**Comment by cbnsti** [comment]
I fixed this problem. But have a new problem, Need HELP!!

PS C:\Users\hunte> python C:\Users\hunte\palworld-save-tools-main\uesave\fix-host-save.py C:\Users\hunte\palworld-save-tools-main\uesave\uesave.exe C:\Users\hunte\OneDrive\Desktop\Temporaru palworld\6FDC94564DDD1A5A5A7C589B3363D2DD 5C94C0F7000000000000000000000000 A93878EF000000000000000000000000 "True"

ERROR: Invalid <guild_fix> argument. It should be either "True" or "False".

I have tried "True" , "False" , True , False ; but nothing works. I get the same ERROR.

**Comment by JannikBirn** [comment]
It looks like you're not using my script here. A <guild_fix> argument is not necessary. You are probably using the script from xNul. Please open an issue there or try to execute my script.
Or you could also download an executable from the latest realese, then you don't have to use the terminal.

**Comment by cbnsti** [comment]
So I have tried every script possible. On many Github, reddit, and youtube pages. I left issues and comments on all. You are the only person to reach back. With all of the scripts I have tried this is the closest. I have also read that with Palworld recent update the Guild Fix is now required in the script. Can you tell me what is different from the script I am using vs yours. I also don't know what you mean by download an executable? I have tried in both CMD terminal and in powershell.

Any help is very much appreciated. I have no knowledge of coding and scripts I am watching many youtube videos and figuring it out on my own, but I am just stuck and me and my friends are just trying to get our stuff back to play palworld again.

**Comment by JannikBirn** [comment]
So you can download a .exe attached to the latest release over here https://github.com/JannikBirn/palworld-host-save-fix/releases
This should be easier to execute then the script.
My script will automatically fix the guilds.

**Comment by cbnsti** [comment]
I have tried this .exe and did all that but I saw no changes.

**Comment by cbnsti** [comment]
So my old character did not appear, I still had the new character, that was supposed to be overwritten. I ran the .exe last night all was a success took about 12 min for the .exe to complete. I replaced the level.sav file in my dedicated pal server with this new one, but it was still the new character.

**Comment by cbnsti** [comment]
I can rerun the .exe file from the orginal back up again and send screenshot and notepad docs of the coding if that helps.

**Comment by cbnsti** [comment]
This time it seemed to have failed. I have uploaded 4 pictures with all the coding from the program.

[16612] Failed to execute script 'gui' due to unhandled exception!

I am not sure what this is.

![exe_file_pic2](https://github.com/JannikBirn/palworld-host-save-fix/assets/159746069/061b0e37-a737-4849-981d-35f1ba6c8945)
![exe_file_pic3](https://github.com/JannikBirn/palworld-host-save-fix/assets/159746069/12052e49-2789-4743-8bf5-865b8c9b4d7a)
![exe_file_pic4](https://github.com/JannikBirn/palworld-host-save-fix/assets/159746069/5ca51699-ab50-494f-a337-f6289584ddc1)
![exe_file_pic1](https://github.com/JannikBirn/palworld-host-save-fix/assets/159746069/05b68655-8453-4f25-8712-8216bea3ca32)

**Comment by cbnsti** [comment]
I was able to force convert the json file back to .sav with the convert.cmd

I then replaced the old level.sav with the new one from the conversion and I started the game and it wanted me to make a new character

**Comment by JannikBirn** [comment]
> I replaced the level.sav file in my dedicated pal server with this new one, but it was still the new character.

You also need to replace the Players folder, have you done that? Only replacing the Level.sav won't work.

**Comment by cbnsti** [comment]
This is the part I'm confused at because wouldn't the player folder be the same nothing was different with the player folder I only changed the level.sav

**Comment by cbnsti** [comment]
I followed  your next step it said complete. I copied over the new save path from my temporary to the server and started everything up. It wants me to create a new character

**Comment by cbnsti** [comment]
I tried again with restarting with the original back up and I switched the coding of the player.sav for the new gui and old gui and this is the error it gave me.

C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main>python "C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\fix-host-save.py" "C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\6FDC94564DDD1A5A5A7C589B3363D2DD" A93878EF000000000000000000000000 0FFCEA56000000000000000000000000 "True"
WARNING: Running this script WILL change your save files and could potentially corrupt your data. It is HIGHLY recommended that you make a backup of your save folder before continuing. Press enter if you would like to continue.
>
Converting C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\6FDC94564DDD1A5A5A7C589B3363D2DD/Level.sav to JSON...Done!
Converting C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\6FDC94564DDD1A5A5A7C589B3363D2DD/Players/0FFCEA56000000000000000000000000.sav to JSON...Traceback (most recent call last):
  File "C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\fix-host-save.py", line 150, in <module>
    main()
  File "C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\fix-host-save.py", line 72, in main
    old_json = sav_to_json(old_sav_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\fix-host-save.py", line 124, in sav_to_json
    raw_gvas, _ = decompress_sav_to_gvas(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hunte\OneDrive\Desktop\Temp Palworld\palworld-host-save-fix-main\palworld_save_tools\palsav.py", line 18, in decompress_sav_to_gvas
    raise Exception(
Exception: not a compressed Palworld save, found too many null bytes, this is likely corrupted

Do you happen to know what I can do from here? or is there just no more hope for the file?
