### ISSUE TITLE
[19008] Failed to execute script 'gui' du

### ISSUE THREAD

**Issue by silverfox0** [JannikBirn/palworld-host-save-fix#46]
when the new update to the game and dedicated server dropped this error started happening 

Loading GVAS file
Struct type for .worldSaveData.InvaderSaveData.Key not found, assuming Guid
Struct type for .worldSaveData.InvaderSaveData.Value not found, assuming StructProperty
Struct type for .worldSaveData.OilrigSaveData.OilrigMap.Value not found, assuming StructProperty
Traceback (most recent call last):
  File "gui.py", line 129, in <module>
  File "gui.py", line 67, in main
  File "fix_host_save.py", line 177, in sav_to_json
  File "convert.py", line 74, in convert_sav_to_json
  File "lib\gvas.py", line 125, in read
  File "lib\archive.py", line 177, in properties_until_end
  File "lib\archive.py", line 188, in property
  File "lib\archive.py", line 300, in struct
  File "lib\archive.py", line 336, in struct_value
  File "lib\archive.py", line 177, in properties_until_end
  File "lib\archive.py", line 278, in property
Exception: Unknown type: UInt32Property (.worldSaveData.WorldMetaSaveVersionBitMask)
[19008] Failed to execute script 'gui' du

**Comment by oseasmoreto** [comment]
I have same problem! :(

**Comment by J-Yoharu** [comment]
This is happening because of the new version, to "fix" I ran the palworld-save-tools script manually, pasted it into the server's save folder and after generating the json, I commented out line 31 of "fix_host_save_py" and ran the script according to read.me

**Comment by GMK96** [comment]
> This is happening because of the new version, to "fix" I ran the palworld-save-tools script manually, pasted it into the server's save folder and after generating the json, I commented out line 31 of "fix_host_save_py" and ran the script according to read.me

Hey man sorry, im going crazy for this, can you explain detailed how to do it? im no pro sorry! :(

**Comment by WakanaPoi** [comment]
> > This is happening because of the new version, to "fix" I ran the palworld-save-tools script manually, pasted it into the server's save folder and after generating the json, I commented out line 31 of "fix_host_save_py" and ran the script according to read.me
> 
> Hey man sorry, im going crazy for this, can you explain detailed how to do it? im no pro sorry! :(

This is my steps:
1.check out palworld-save-tools, find convert.py file, then running python convert.py path_to_your_Level.sav in terminal to generate sav.json file
2.remove 
`if` os.path.exists(level_json_path):
                    os.remove(level_json_path)
                sav_to_json(level_sav_path, level_json_path)

**Comment by WakanaPoi** [comment]
This is my steps:
1.check out palworld-save-tools, find convert.py file, then running python convert.py path_to_your_Level.sav in terminal to generate sav.json file
2.remove
```
if os.path.exists(level_json_path):
os.remove(level_json_path)
sav_to_json(level_sav_path, level_json_path)
```

**Comment by WakanaPoi** [comment]
This is my steps:
1.check out palworld-save-tools, find convert.py file, then running python convert.py path_to_your_Level.sav in terminal to generate sav.json file
2.remove
```
if os.path.exists(level_json_path):
os.remove(level_json_path)
sav_to_json(level_sav_path, level_json_path)
```
this lines in gui.py and then run, operates left are same with what in readme

**Comment by FMerveille** [comment]
I'm facing the same issue. Could someone share a fix for this ?

**Comment by sczombie** [comment]
> This is my steps: 1.check out palworld-save-tools, find convert.py file, then running python convert.py path_to_your_Level.sav in terminal to generate sav.json file 2.remove
> 
> ```
> if os.path.exists(level_json_path):
> os.remove(level_json_path)
> sav_to_json(level_sav_path, level_json_path)
> ```
> 
> this lines in gui.py and then run, operates left are same with what in readme

Hi I'm trying to follow your instructions but I can't find gui.py in either palworld-save-tools or palworld-host-save-fix. Can you help me figure out where to look for this script?

**Comment by murd3rb0t** [comment]
> > This is my steps: 1.check out palworld-save-tools, find convert.py file, then running python convert.py path_to_your_Level.sav in terminal to generate sav.json file 2.remove
> > ```
> > if os.path.exists(level_json_path):
> > os.remove(level_json_path)
> > sav_to_json(level_sav_path, level_json_path)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this lines in gui.py and then run, operates left are same with what in readme
> 
> Hi I'm trying to follow your instructions but I can't find gui.py in either palworld-save-tools or palworld-host-save-fix. Can you help me figure out where to look for this script?

Not sure if you've worked through it or not but the gui.py file is in the repository that you'll need to clone from git hub into your IDE with gitbash to edit
